import{a as M}from"./assets/vendor-B1ZHW564.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const i of document.querySelectorAll('link[rel="modulepreload"]'))s(i);new MutationObserver(i=>{for(const n of i)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(i){const n={};return i.integrity&&(n.integrity=i.integrity),i.referrerPolicy&&(n.referrerPolicy=i.referrerPolicy),i.crossOrigin==="use-credentials"?n.credentials="include":i.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(i){if(i.ep)return;i.ep=!0;const n=o(i);fetch(i.href,n)}})();const w="https://api.themoviedb.org/3",N="/trending/movie/day",I="/genre/movie/list",L="eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlZGIyYTJjMDMxMTM4ZmM0MmFjNzZiNTBjYjM2MzYzYyIsIm5iZiI6MTc3ODUxMjkyMi44OTIsInN1YiI6IjZhMDFmNDFhMmNmMzU0MjMwMmNhYmQzZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.-EXygFMgjTxyEK5u7kl9Fa5C2gS46ahwf8XKIyNNPb0";let f={};async function $(t){const{data:e}=await M.get(`${w}${N}`,{params:{page:`${t}`},headers:{accept:"application/json",Authorization:`Bearer ${L}`}});return e}async function O(){const{data:t}=await M.get(`${w}${I}`,{params:{language:"en"},headers:{accept:"application/json",Authorization:`Bearer ${L}`}});return t}async function j(){try{const{genres:t}=await O();f=t.reduce((o,s)=>(o[s.id]=s.name,o),{})}catch(t){console.log(t)}}const b=document.querySelector(".load-more-btn");function E(t){return t.map(({id:e,poster_path:o,original_title:s,release_date:i,overview:n,genre_ids:c})=>`
            <li class="movie-list-item" data-id=${e}>
                <div class="movie-img-wrapper">
                    <img class="movie-img" src="https://image.tmdb.org/t/p/w500${o}" alt="${s}"/>
                    <p class="movie-item-text">${n}</p>
                </div>
                <div class="movie-content">
                    <h4 class="movie-title">${s}</h4>
                    <div class="movie-info">
                        <p class="release-date">${i.split("-")[0]}</p>
                        <p class="movie-genre">${f[c[0]]?`&nbsp;| ${f[c[0]]}`:""}</p>
                    </div>
                </div>
            </li>
        `).join("")}function x(){b.classList.remove("hidden")}function y(){b.classList.add("hidden")}const a=document.querySelector(".movie-list"),p=document.querySelector(".load-more-btn"),B=document.querySelector(".next-btn"),S=document.querySelector(".prev-btn"),g=document.querySelector(".movie-list-container");let l=[],d=0,u=1,m=!1,r=0;const W=218,J=24,h=W+J;async function T(){await j(),await v()}T();async function v(){if(p.disabled=!0,l.length-d<6&&!m)try{const e=await $(u);if(!e||!e.results)return;u===1&&x(),u>=e.total_pages&&(m=!0),l=[...l,...e.results],u++}catch(e){console.log(e.message),y()}const t=l.slice(d,d+6);t.length>0&&(a.insertAdjacentHTML("beforeend",E(t)),d+=t.length),window.innerWidth<1200&&(m&&d>=l.length?y():p.disabled=!1)}p.addEventListener("click",v);a.addEventListener("click",t=>{const e=t.target.closest(".movie-list-item");if(!e)return;const o=e.classList.contains("is-visible");document.querySelectorAll(".movie-list-item.is-visible").forEach(s=>{s.classList.remove("is-visible")}),o||e.classList.add("is-visible")});B.addEventListener("click",async()=>{if(window.innerWidth<1200)return;const t=-(a.scrollWidth-g.clientWidth);r<=t+h*3&&!m&&await v();const e=-(a.scrollWidth-g.clientWidth);r>e&&(r-=h,a.style.transform=`translateX(${r}px)`)});S.addEventListener("click",()=>{window.innerWidth<1200||r<0&&(r+=h,a.style.transform=`translateX(${r}px)`)});
//# sourceMappingURL=index.js.map
