import{a as p}from"./assets/vendor-B1ZHW564.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const g="https://api.themoviedb.org/3",N="/trending/movie/day",I="/genre/movie/list",h="eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlZGIyYTJjMDMxMTM4ZmM0MmFjNzZiNTBjYjM2MzYzYyIsIm5iZiI6MTc3ODUxMjkyMi44OTIsInN1YiI6IjZhMDFmNDFhMmNmMzU0MjMwMmNhYmQzZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.-EXygFMgjTxyEK5u7kl9Fa5C2gS46ahwf8XKIyNNPb0";let u={};async function L(i){const{data:e}=await p.get(`${g}${N}`,{params:{page:`${i}`},headers:{accept:"application/json",Authorization:`Bearer ${h}`}});return e}async function b(){const{data:i}=await p.get(`${g}${I}`,{params:{language:"en"},headers:{accept:"application/json",Authorization:`Bearer ${h}`}});return i}async function $(){try{const{genres:i}=await b();u=i.reduce((r,s)=>(r[s.id]=s.name,r),{})}catch(i){console.log(i)}}const v=document.querySelector(".load-more-btn");function j(i){return i.map(({id:e,poster_path:r,original_title:s,release_date:t,overview:o,genre_ids:n})=>`
            <li class="movie-list-item" data-id=${e}>
                <div class="movie-img-wrapper">
                    <img class="movie-img" src="https://image.tmdb.org/t/p/w500${r}" alt="${s}"/>
                    <p class="movie-item-text">${o}</p>
                </div>
                <div class="movie-content">
                    <h4 class="movie-title">${s}</h4>
                    <div class="movie-info">
                        <p class="release-date">${t.split("-")[0]}</p>
                        <p class="movie-genre">${u[n[0]]?`&nbsp;| ${u[n[0]]}`:""}</p>
                    </div>
                </div>
            </li>
        `).join("")}function w(){v.classList.remove("hidden")}function f(){v.classList.add("hidden")}const y=document.querySelector(".movie-list"),m=document.querySelector(".load-more-btn");let a=[],c=0,l=1,d=!1;async function O(){await $(),await M()}O();async function M(){if(m.disabled=!0,a.length-c<6&&!d)try{const e=await L(l);if(!e||!e.results)return;l===1&&w(),l>=e.total_pages&&(d=!0),a=[...a,...e.results],l++}catch(e){console.log(e.message),f()}const i=a.slice(c,c+6);y.insertAdjacentHTML("beforeend",j(i)),c+=i.length,d&&c>=a.length?f():m.disabled=!1}m.addEventListener("click",M);y.addEventListener("click",i=>{const e=i.target.closest(".movie-list-item");if(console.log(e),!e)return;const r=e.classList.contains("is-visible");document.querySelectorAll(".movie-list-item.is-visible").forEach(s=>{s.classList.remove("is-visible")}),r||e.classList.add("is-visible")});
//# sourceMappingURL=index.js.map
