import{a as v,i as M}from"./assets/vendor-DfocyEbf.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))n(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const r of o.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&n(r)}).observe(document,{childList:!0,subtree:!0});function i(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(s){if(s.ep)return;s.ep=!0;const o=i(s);fetch(s.href,o)}})();const g="https://api.themoviedb.org/3",I="/trending/movie/day",B="/genre/movie/list",F="/search/movie",b="eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlZGIyYTJjMDMxMTM4ZmM0MmFjNzZiNTBjYjM2MzYzYyIsIm5iZiI6MTc3ODUxMjkyMi44OTIsInN1YiI6IjZhMDFmNDFhMmNmMzU0MjMwMmNhYmQzZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.-EXygFMgjTxyEK5u7kl9Fa5C2gS46ahwf8XKIyNNPb0";let h={};async function T(t){const{data:e}=await v.get(`${g}${I}`,{params:{page:t},headers:{accept:"application/json",Authorization:`Bearer ${b}`}});return e}async function A(){const{data:t}=await v.get(`${g}${B}`,{params:{language:"en"},headers:{accept:"application/json",Authorization:`Bearer ${b}`}});return t}async function O(){try{const{genres:t}=await A();h=t.reduce((i,n)=>(i[n.id]=n.name,i),{})}catch(t){console.log(t)}}async function j(t){const{data:e}=await v.get(`${g}${F}`,{params:{query:t,include_adult:!0,language:"en"},headers:{accept:"application/json",Authorization:`Bearer ${b}`}});return e}const $=document.querySelector(".load-more-btn");function q(t){return t.map(({id:e,poster_path:i,original_title:n,release_date:s,overview:o,genre_ids:r})=>`
            <li class="movie-list-item" data-id=${e}>
                <div class="movie-img-wrapper">
                    <img class="movie-img" src="https://image.tmdb.org/t/p/w500${i}" alt="${n}"/>
                    <p class="movie-item-text">${o}</p>
                </div>
                <div class="movie-content">
                    <h4 class="movie-title">${n}</h4>
                    <div class="movie-info">
                        <p class="release-date">${s.split("-")[0]}</p>
                        <p class="movie-genre">${h[r[0]]?`&nbsp;| ${h[r[0]]}`:""}</p>
                    </div>
                </div>
            </li>
        `).join("")}function C(){$.classList.remove("hidden")}function w(){$.classList.add("hidden")}function x(t){return t.map(({title:e,release_date:i,vote_average:n})=>`
        <li class="search-section-item">
            <a href="#" class="search-item-link">
                <span class="movie-name">${e}</span>
                <span class="movie-year">${i?i.split("-")[0]:"n/a"}</span>
                <span class="movie-rating">${n.toFixed(2)}</span>
            </a>
        </li>
        `).join("")}function z(t,e){return function(...n){let s=this.lastCall;this.lastCall=Date.now(),s&&this.lastCall-s<=e&&clearTimeout(this.lastCallTimer),this.lastCallTimer=setTimeout(()=>t(...n),e)}}const f=document.querySelector("#search-results"),S=document.querySelector(".search-section-list");function P(){const t=document.querySelector("#search"),e=document.querySelector("#search-field"),i=document.querySelector(".search-open-btn"),n=document.querySelector(".sidebar-open-btn"),s=document.querySelector("#search-results");if(!t||!i)return;i.addEventListener("click",r=>{r.stopPropagation(),t.classList.add("is-focused"),n.style.display="none",e.focus()}),document.addEventListener("click",r=>{t.contains(r.target)||(t.classList.remove("is-focused"),n.style.display="block",s.classList.remove("is-visible"),e.value="")});const o=z(W,500);e.addEventListener("input",o)}async function W(t){const e=t.target.value.trim();if(e.length===0){S.innerHTML="",f.classList.remove("is-visible");return}try{const{results:i}=await j(e);if(!i.length){f.classList.remove("is-visible"),M.show({title:"We could not find anything.",message:"Maybe you should try a different search term?",color:"#EF4040",messageColor:"#FAFAFB",titleColor:"#FAFAFB"});return}S.innerHTML=x(i),f.classList.add("is-visible")}catch(i){M.show({color:"#EF4040",messageColor:"#FAFAFB",message:`${i.message}`})}}const d=document.querySelector(".movie-list"),p=document.querySelector(".load-more-btn"),D=document.querySelector(".next-btn"),J=document.querySelector(".prev-btn"),N=document.querySelector(".movie-list-container");let c=[],l=0,u=1,m=!1,a=0;const k=218,Z=24,y=k+Z;async function G(){await O(),await L()}G();P();async function L(){if(p.disabled=!0,c.length-l<6&&!m)try{const e=await T(u);if(!e||!e.results)return;u===1&&C(),u>=e.total_pages&&(m=!0),c=[...c,...e.results],u++}catch(e){console.log(e.message),w()}const t=c.slice(l,l+6);t.length>0&&(d.insertAdjacentHTML("beforeend",q(t)),l+=t.length),window.innerWidth<1200&&(m&&l>=c.length?w():p.disabled=!1)}p.addEventListener("click",L);d.addEventListener("click",t=>{const e=t.target.closest(".movie-list-item");if(!e)return;const i=e.classList.contains("is-visible");document.querySelectorAll(".movie-list-item.is-visible").forEach(n=>{n.classList.remove("is-visible")}),i||e.classList.add("is-visible")});const R=()=>{d.style.transform=`translateX(${a}px)`};function E(t){if(!(window.innerWidth<1200)){if(t==="next"){const e=-(d.scrollWidth-N.clientWidth);a>e&&(a-=y)}else t==="back"&&a<0&&(a+=y);R()}}D.addEventListener("click",async()=>{const t=-(d.scrollWidth-N.clientWidth);a<=t+y*3&&!m&&await L(),E("next")});J.addEventListener("click",()=>E("back"));
//# sourceMappingURL=index.js.map
